###
# @name createAsset
POST http://localhost:3000/assets
Content-Type: application/json

{
  "name": "test",
  "symbol":  "test",
  "price": 100,
  "image": "https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png"
}

###

@assetId = {{ createAsset.response.body.id }}

###
GET http://localhost:3000/assets

###
GET http://localhost:3000/assets/test

###
# @name createWallet
POST http://localhost:3000/wallets
Content-Type: application/json

###

@walletId = {{ createWallet.response.body.id }}

GET http://localhost:3000/wallets

###
GET http://localhost:3000/wallets/{{walletId}}

###
# @name createWallet
POST http://localhost:3000/wallets/{{walletId}}/assets
Content-Type: application/json

{
  "assetId": "{{ assetId }}",
  "shares": 100
}


###
POST http://localhost:3000/orders
Content-Type: application/

{
  "walletId": "{{ walletId }}",
  "assetId": "{{ assetId }}",
  "shares": 10,
  "price": 100,
  "type": "BUY"
}


###
GET http://localhost:3000/orders?walletId={{ walletId }}
